import type { ModelCatalogItem } from "../types";

export const DEFAULT_MODELS: ModelCatalogItem[] = [
  {
    provider: "openai",
    model: "gpt-4o",
    tier: "frontier",
    input_cost_per_1m: 0,
    output_cost_per_1m: 0,
    context_limit: 128000,
    tags: ["legacy"],
    enabled: true,
    supports_image_input: true,
    supported_attachment_mime_types: [],
  },
  {
    provider: "gemini",
    model: "gemini-2.5-flash",
    tier: "frontier",
    input_cost_per_1m: 0,
    output_cost_per_1m: 0,
    context_limit: 128000,
    tags: ["fastest"],
    enabled: true,
    supports_image_input: true,
    supported_attachment_mime_types: [],
  },
  {
    provider: "grok",
    model: "grok-4-1-fast-non-reasoning",
    tier: "frontier",
    input_cost_per_1m: 0,
    output_cost_per_1m: 0,
    context_limit: 128000,
    tags: ["raw"],
    enabled: true,
    supports_image_input: false,
    supported_attachment_mime_types: [],
  },
];
