import type { ModelCatalogItem } from "../types";

export const DEFAULT_MODELS: ModelCatalogItem[] = [
  {
    provider: "openai",
    model: "gpt-5.1",
    tier: "frontier",
    billing_class: "advanced",
    access_category: "advanced",
    input_credit_multiplier: 3,
    output_credit_multiplier: 12,
    credit_usage_label: "High",
    credit_pricing_version: "2026-07-29",
    input_cost_per_1m: 0,
    output_cost_per_1m: 0,
    context_limit: 128000,
    tags: ["preferred-compare"],
    enabled: true,
    supports_image_input: true,
    supported_attachment_mime_types: [],
  },
  {
    provider: "claude",
    model: "claude-sonnet-4-5",
    tier: "frontier",
    billing_class: "advanced",
    access_category: "advanced",
    input_credit_multiplier: 4,
    output_credit_multiplier: 18,
    credit_usage_label: "High",
    credit_pricing_version: "2026-07-29",
    input_cost_per_1m: 0,
    output_cost_per_1m: 0,
    context_limit: 128000,
    tags: ["preferred-compare"],
    enabled: true,
    supports_image_input: true,
    supported_attachment_mime_types: [],
  },
  {
    provider: "deepseek",
    model: "deepseek-chat",
    tier: "frontier",
    billing_class: "economical",
    access_category: "economical",
    input_credit_multiplier: 0.5,
    output_credit_multiplier: 1,
    credit_usage_label: "Very low",
    credit_pricing_version: "2026-07-29",
    input_cost_per_1m: 0,
    output_cost_per_1m: 0,
    context_limit: 128000,
    tags: ["preferred-compare-add"],
    enabled: true,
    supports_image_input: false,
    supported_attachment_mime_types: [],
  },
];
