"""
Database package for CortexAI.
Provides SQLAlchemy engine, session management, table reflection, and repository functions.
"""

from db.engine import get_engine
from db.billing_repository import (
    ALLOWED_USAGE_METERS,
    LIVE_SUBSCRIPTION_STATUSES,
    SubscriptionSnapshot,
    close_usage_period,
    create_usage_period,
    create_usage_reservation,
    create_webhook_event_if_absent,
    expire_usage_reservation,
    get_active_usage_period,
    get_billing_account_by_id,
    get_billing_account_by_stripe_customer_id,
    get_billing_account_for_user,
    get_latest_subscription_for_account,
    get_live_subscription_for_account,
    get_or_create_billing_account_for_user,
    get_or_create_usage_period,
    get_or_create_usage_counter,
    get_subscription_by_provider_id,
    get_usage_reservation,
    get_usage_reservation_by_id,
    lock_billing_account,
    lock_webhook_event,
    lock_stale_usage_reservations,
    lock_usage_counters,
    mark_webhook_event_failed,
    mark_webhook_event_processed,
    release_usage_reservation,
    release_usage_quantities,
    reserve_usage_quantities,
    set_stripe_customer_id,
    settle_usage_reservation,
    settle_usage_quantities,
    synchronize_usage_period,
    upsert_subscription_snapshot,
)
from db.repository import (
    create_request_attachment,
    create_uploaded_file,
    clear_llm_history,
    check_usage_limit,
    compute_context_hash,
    compute_api_key_hash,
    create_api_key,
    delete_byok_provider_keys,
    create_routing_attempts,
    create_routing_decision,
    # Utility
    compute_prompt_sha256,
    create_context_snapshot,
    # LLM Audit
    create_llm_request,
    create_llm_response,
    delete_llm_history_entry,
    enqueue_file_deletion_job,
    find_active_uploaded_file_by_hash,
    generate_api_key,
    get_api_key_settings,
    # Session Management
    create_session,
    get_active_session,
    # Context Snapshots
    get_latest_context_snapshot,
    get_llm_history_entries,
    rename_history_session,
    # User & Auth
    get_or_create_cli_user,
    get_or_create_service_user,
    get_or_create_user_by_cognito,
    get_byok_provider_key,
    get_failed_routing_attempts_by_request_group,
    get_savings_aggregates,
    get_session_by_id,
    get_session_messages,
    get_uploaded_file_by_id,
    get_uploaded_file_for_user,
    get_usage_aggregates,
    list_byok_provider_keys,
    list_due_file_deletion_jobs,
    list_expired_uploaded_files,
    list_request_attachments_for_request,
    # Usage Tracking
    get_usage_daily,
    get_user_by_api_key,  # Returns (user_id, api_key_id) tuple
    # User Preferences
    get_user_preferences,
    # Compare Mode
    save_compare_summary,
    # Message Management
    save_message,
    update_api_key_last_used,
    update_file_deletion_job,
    update_uploaded_file_status,
    update_session_timestamp,
    upsert_usage_daily,
    upsert_api_key_settings,
    upsert_byok_provider_key,
    upsert_llm_savings,
    verify_session_belongs_to_user,
)
from db.session import SessionLocal, get_db
from db.tables import (
    get_table,
    # Individual table getters exported via __getattr__ in tables.py
    metadata,
)

__all__ = [
    "ALLOWED_USAGE_METERS",
    "LIVE_SUBSCRIPTION_STATUSES",
    "SessionLocal",
    "SubscriptionSnapshot",
    "check_usage_limit",
    "clear_llm_history",
    "close_usage_period",
    "compute_api_key_hash",
    "compute_context_hash",
    "compute_prompt_sha256",
    "create_api_key",
    "create_context_snapshot",
    "create_llm_request",
    "create_llm_response",
    "create_request_attachment",
    "create_routing_attempts",
    "create_routing_decision",
    "create_session",
    "create_uploaded_file",
    "create_usage_period",
    "create_usage_reservation",
    "create_webhook_event_if_absent",
    "delete_byok_provider_keys",
    "delete_llm_history_entry",
    "enqueue_file_deletion_job",
    "expire_usage_reservation",
    "find_active_uploaded_file_by_hash",
    "generate_api_key",
    "get_active_session",
    "get_active_usage_period",
    "get_api_key_settings",
    "get_billing_account_by_id",
    "get_billing_account_by_stripe_customer_id",
    "get_billing_account_for_user",
    "get_byok_provider_key",
    "get_db",
    "get_engine",
    "get_failed_routing_attempts_by_request_group",
    "get_latest_context_snapshot",
    "get_latest_subscription_for_account",
    "get_live_subscription_for_account",
    "get_llm_history_entries",
    "get_or_create_billing_account_for_user",
    "get_or_create_cli_user",
    "get_or_create_service_user",
    "get_or_create_usage_counter",
    "get_or_create_usage_period",
    "get_or_create_user_by_cognito",
    "get_savings_aggregates",
    "get_session_by_id",
    "get_session_messages",
    "get_subscription_by_provider_id",
    "get_table",
    "get_uploaded_file_by_id",
    "get_uploaded_file_for_user",
    "get_usage_aggregates",
    "get_usage_daily",
    "get_usage_reservation",
    "get_usage_reservation_by_id",
    "get_user_by_api_key",
    "get_user_preferences",
    "list_byok_provider_keys",
    "list_due_file_deletion_jobs",
    "list_expired_uploaded_files",
    "list_request_attachments_for_request",
    "lock_billing_account",
    "lock_stale_usage_reservations",
    "lock_usage_counters",
    "lock_webhook_event",
    "mark_webhook_event_failed",
    "mark_webhook_event_processed",
    "metadata",
    "release_usage_quantities",
    "release_usage_reservation",
    "rename_history_session",
    "reserve_usage_quantities",
    "save_compare_summary",
    "save_message",
    "set_stripe_customer_id",
    "settle_usage_quantities",
    "settle_usage_reservation",
    "synchronize_usage_period",
    "update_api_key_last_used",
    "update_file_deletion_job",
    "update_session_timestamp",
    "update_uploaded_file_status",
    "upsert_api_key_settings",
    "upsert_byok_provider_key",
    "upsert_llm_savings",
    "upsert_subscription_snapshot",
    "upsert_usage_daily",
    "verify_session_belongs_to_user",
]
